### ISSUE TITLE
Include a more comprehensive template in the opened file

### ISSUE THREAD

**Issue by wxtim** [goodevilgenius/tagedit#6]
It would be useful to provide more commented template lines in the editor.

**Comment by goodevilgenius** [comment]
Specifically, what more information do you want in there?

**Comment by wxtim** [comment]
A list of possible fields might be nice.

**Comment by goodevilgenius** [comment]
vorbis comments are free form, so you can include any field.
available id3 tags can easily be looked up.

That said, I'd be willing to look at any PRs.
