### ISSUE TITLE
id3v2 parameter -R not recognized

### ISSUE THREAD

**Issue by Konfekt** [goodevilgenius/tagedit#8]
Hello, there seem to be different versions of id3v2 floating around: on Opensuse 15.3 id3v2 does not recognize the parameter `-R` where that from, say, Debian does. They output the same version information, but `--help` shows that `-R` is not listed on the Opensuse build. Maybe a compile time option.

**Comment by goodevilgenius** [comment]
@Konfekt I'm not really using this tool anymore, so I don't really plan on making any changes/fixes.

If you'd like to submit a PR, I'll review it and merge it in.

**Comment by goodevilgenius** [comment]
Also, see #4

**Comment by Konfekt** [comment]
Oh, thank you, I did not  look at the resolved issues. Is there a better program to mass edit tags in an editor now?

**Comment by goodevilgenius** [comment]
No idea. It's just not something I do much anymore. I usually just write a quick bash loop.

And `tagedit` only supports mp3 and ogg, but I almost exclusively use aac and opus now.

Sorry I can't be more help.

**Comment by mrksmrtn** [comment]
> Is there a better program to mass edit tags in an editor now?

I recommend [beets](https://beets.io) which uses the MusicBrainz database to automatically tag your music. I used to be meticulous about hand editing my music tags, but I've found that I am much better off this way in terms of time and fixing metadata in the MB database helps out other people too. That said, it has [a plugin for mass tag editing](https://beets.readthedocs.io/en/stable/plugins/edit.html) if you find yourself needing it or prefer not to venture into autotagging. I use it sometimes to make fixes (in Vim) prior to them being accepted by MB.

The only downside is that initially "importing" your collection with beets (i.e.: tagging) may suggest a lot of changes to your collection (like Unicode characters replacing ASCII ones, label data added that often needs the release country hand modified, etc), but you can import your music "as-is" and then just use beets for mass tag editing. If you're concerned, always use the "timid" flag (or add it to the config).

The autotagging has turned up some pretty big discrepancies in my collection though.. Such as track names being rather wrong. Then one album had a track that I had been listening to for years with a completely wrong title. It will let know if you have missing tracks and (depending on the MB database quality) figures out whether you have some kind of deluxe release with extra tracks, etc, etc..
